### ISSUE TITLE
'db' command does not support MariaDB

### ISSUE THREAD

**Issue by dittertp** [valet-sh/valet-sh#224]
**Repro:**

- Make sure the default database service is not mariadb104
- Initialize a new project (i.e. execute valet.sh init)
- In the resulting .valet-sh.yml configure the following:
```
services:
  mariadb:
    version: 10.4
    database: "mydatabase"
```
- Make sure that the path services.mysql does not exists in .valet-sh.yml
- Create the database (i.e. execute valet.sh db create mydatabase)

**Expected:**
The database is created in the service mariadb104

**Actual:**

The database is created in the service mysql57
